sudo: false
dist: trusty

language: node_js

node_js:
  - 8.9.4

install:
  - npm install
  - npm install -g vsce
  - npm run compile
  - npm run compile-lint
  - npm run test
  - vsce package
 
deploy:
  - provider: script
    script: cp ./src/pslLint/cli/.npmrc.psl-lint .npmrc && npm pack ./src/pslLint/cli | xargs npm publish
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^psl-lint
      all_branches: true
      repo: ing-bank/vscode-psl
  - provider: script
    script: vsce publish -p $VSCODE_TOKEN
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^vscode-psl
      all_branches: true
      repo: ing-bank/vscode-psl
